#!/usr/bin/env python3
import re
import sys
from collections.abc import Iterable, Iterator

from dataclasses import dataclass
from enum import Enum, StrEnum
from itertools import chain
from pathlib import Path
from typing import Collection, Final, NamedTuple


@dataclass
class Arguments:
    space_char: str
    files: Collection[Path]
    directories: Collection[Path]
    action: Action
    debug: bool
    color: bool
    recursive: bool


class Action(StrEnum):
    DO = "do"
    DRY_RUN = "dry-run"


def parse_args(argv: list[str]) -> Arguments:
    from argparse import ArgumentParser

    parser = ArgumentParser(
        description="Sanitize the given file name",
    )
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--no-color", action="store_true")
    parser.add_argument(
        "-r",
        "--recursive",
        action="store_true",
        help="Recurse into each given directories",
    )
    parser.add_argument(
        "-s",
        "--space-char",
        type=str,
        default="_",
        help="The space replacement character",
    )
    parser.add_argument(
        "-f", "--file", type=Path, action="append", help="rename given file"
    )
    parser.add_argument(
        "-d",
        "--directory",
        type=Path,
        action="append",
        help="renamme all files in given directory",
    )
    parser.add_argument(
        "action",
        choices=[action.value for action in Action],
        default=Action.DRY_RUN.value,
        nargs="?",
    )

    parsed = parser.parse_args(argv)

    return Arguments(
        space_char=parsed.space_char,
        files=parsed.file or (),
        directories=parsed.directory or (() if parsed.file else [Path(".")]),
        action=Action(parsed.action),
        debug=parsed.debug,
        color=not parsed.no_color,
        recursive=parsed.recursive,
    )


def main() -> None:
    args = parse_args(sys.argv[1:])

    sanitizer = Sanitizer(args.space_char, args.debug, args.recursive)
    output = Output(args.debug, args.color)

    files = chain(
        sanitizer.sanitize_files(args.files),
        sanitizer.sanitize_directories(args.directories),
    )

    original: Path
    sanitized: Path
    for original, sanitized in sorted(files, key=lambda file: file.sanitized):
        output.pprint(original, sanitized)

        if args.action == Action.DO and original != sanitized:
            original.move(sanitized)


class Output:
    def __init__(self, debug: bool, color: bool) -> None:
        self.debug: Final = debug

        self.green: Final = Color.GREEN.colorize if color else lambda s: s
        self.blue: Final = Color.BLUE.colorize if color else lambda s: s
        self.yellow: Final = Color.YELLOW.colorize if color else lambda s: s
        self.magenta: Final = Color.MAGENTA.colorize if color else lambda s: s

    def pprint(self, original: Path, sanitized: Path) -> None:
        if original == sanitized:
            if self.debug:
                print(original, "-->>   nothing to do")
            return

        print(
            (
                self.magenta(self._format(original))
                if original.is_dir()
                else self.green(original)
            ),
            self.yellow("  -->>  "),
            self.blue(self._format(sanitized)),
        )

    @staticmethod
    def _format(path: Path) -> str:
        return str(path) + ("/" if path.is_dir() else "")


class Sanitizer:
    strip_chars: Final = " ._-"

    def __init__(self, space_char: str, debug: bool, recursive: bool) -> None:
        self.space_char: Final = space_char
        self.debug: Final = debug
        self.recursive: Final = recursive

        self.patterns: Final = (
            (re.compile(r"^\[\s*[a-zA-Z0-9]+\.\w+\s*]"), ""),
            (re.compile(r"[=!]"), ""),
            (re.compile(r"\s+"), self.space_char),
            (re.compile(r"[\][()%]"), self.space_char),
            (re.compile(r"\.{2,}"), "."),
            (re.compile(r"\.?-\."), "-"),
            (re.compile(r"[._-]"), self.space_char),
            (
                re.compile(f"{self.space_char if self.space_char != '.' else r'\.'}+"),
                self.space_char,
            ),
        )

    def sanitize_directories(
        self, directories: Iterable[Path]
    ) -> Iterator[SanitizedFile]:
        for directory in directories:
            yield from self.sanitize_directory(directory)

    def sanitize_files(self, files: Iterable[Path]) -> Iterator[SanitizedFile]:
        for file in files:
            yield self.sanitize_file(file)

    def sanitize_directory(self, directory: Path) -> Iterator[SanitizedFile]:
        for file in directory.iterdir():
            if self.recursive and file.is_dir():
                yield from self.sanitize_directory(file)

            yield self.sanitize_file(file)

    def sanitize_file(self, file: Path) -> SanitizedFile:
        return SanitizedFile(
            file, file.with_name(self.sanitize_name(file.stem) + file.suffix)
        )

    def sanitize_name(self, name: str) -> str:
        name = name.strip(self.strip_chars)
        for reg, repl in self.patterns:
            name = reg.sub(repl, name)

        return name.replace("'", "’").strip(self.strip_chars).lower()


class SanitizedFile(NamedTuple):
    original: Path
    sanitized: Path


class Color(Enum):
    RESET = "\033[00m"

    BLACK = "\033[30m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[34m"
    MAGENTA = "\033[35m"
    CYAN = "\033[36m"
    WHITE = "\033[37m"

    def colorize(self, string: str | Path) -> str:
        return f"{self.value}{string}{Color.RESET.value}"


if __name__ == "__main__":
    main()
